//package Biblioteca;
//import com.bolivia.login.system.User;
//import com.bolivia.login.system.Users;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//import java.awt.event.MouseEvent;
//import java.awt.event.MouseListener;
///**
// * @web http://www.jc-mouse.net/
// * @author Mouse
// */
//public class LoginFrm extends javax.swing.JFrame {
//    
//    private User user;
//    private Users users = new Users();
//    
//    /**
//     * Creates new form LoginFrm
//     */
//    public LoginFrm() {
//        initComponents();
//        
//        setTitle("Inicio de sesión [http://www.jc-mouse.net/]");
//        setLocationRelativeTo(null);
//        
//        //acciones para el slider ------------------------------------------     
//        //boton "validar usuario"
//        jCSlidePanel1.userPanel.getButtonNext().addActionListener(new ActionListener() {
//                    @Override
//                    public void actionPerformed(ActionEvent e) {     
//                        //realiza autenticacion de nick de usuario
//                        user = users.validateUser( jCSlidePanel1.userPanel.getUser() );
//                        if( user!=null ){
//                            jCSlidePanel1.userPanel.showError("");
//                            jCSlidePanel1.passPanel.showError("");                            
//                            jCSlidePanel1.passPanel.setPhoto(user.getPhoto());
//                            jCSlidePanel1.passPanel.setUser(user.getName());
//                            jCSlidePanel1.passPanel.setMail(user.getMail());
//                            jCSlidePanel1.moveLeft();
//                        }      
//                        else
//                        {
//                            jCSlidePanel1.userPanel.showError("El nombre de usuario es incorrecto");
//                        }
//                    }
//                });
//        
//        //validar password
//        jCSlidePanel1.passPanel.getButtonPass().addActionListener(new ActionListener() {
//                    @Override
//                    public void actionPerformed(final ActionEvent e) {    
//                        //si contraseña es correcta
//                        if(jCSlidePanel1.passPanel.getPassword().equals( user.getPassword() ) )
//                        {                            
//                            dispose();
//                            //muestra formulario principal
//                            new AppFrm().setVisible(true);
//                        }
//                        else
//                        {
//                            jCSlidePanel1.passPanel.showError("El password e incorrecto");
//                        }
//                    }
//                });
//        
//        //retroceed a panel USUARIO
//        jCSlidePanel1.passPanel.getCommand().addMouseListener( new MouseListener(){
//
//            @Override
//            public void mouseClicked(MouseEvent e) {               
//                jCSlidePanel1.moveRight();
//            }
//
//            @Override
//            public void mousePressed(MouseEvent e) {/*...*/}
//
//            @Override
//            public void mouseReleased(MouseEvent e) {/*...*/}
//
//            @Override
//            public void mouseEntered(MouseEvent e) {/*...*/}
//
//            @Override
//            public void mouseExited(MouseEvent e) {/*...*/}
//            
//        });  
//    }//LoginFrm:end
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//        java.awt.GridBagConstraints gridBagConstraints;
//
//        jPanel2 = new javax.swing.JPanel();
//        jPanel1 = new javax.swing.JPanel();
//        jCSlidePanel1 = new com.bolivia.login.swing.JCSlidePanel();
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
//
//        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
//        jPanel2.setLayout(new java.awt.GridBagLayout());
//
//        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
//        jPanel1.setPreferredSize(new java.awt.Dimension(360, 322));
//        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
//        jPanel1.add(jCSlidePanel1);
//
//        gridBagConstraints = new java.awt.GridBagConstraints();
//        gridBagConstraints.gridx = 0;
//        gridBagConstraints.gridy = 2;
//        gridBagConstraints.insets = new java.awt.Insets(0, 40, 40, 40);
//        jPanel2.add(jPanel1, gridBagConstraints);
//
//        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
//        jLabel1.setForeground(new java.awt.Color(85, 85, 85));
//        jLabel1.setText("Gooogle, Inc.");
//        gridBagConstraints = new java.awt.GridBagConstraints();
//        gridBagConstraints.gridx = 0;
//        gridBagConstraints.gridy = 0;
//        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
//        jPanel2.add(jLabel1, gridBagConstraints);
//
//        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
//        jLabel2.setForeground(new java.awt.Color(85, 85, 85));
//        jLabel2.setText("iniciar sesión para comenzar a ganarse el pan");
//        gridBagConstraints = new java.awt.GridBagConstraints();
//        gridBagConstraints.gridx = 0;
//        gridBagConstraints.gridy = 1;
//        gridBagConstraints.insets = new java.awt.Insets(12, 0, 12, 0);
//        jPanel2.add(jLabel2, gridBagConstraints);
//
//        getContentPane().add(jPanel2);
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginFrm().setVisible(true);
//            }
//        });
//    }
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private com.bolivia.login.swing.JCSlidePanel jCSlidePanel1;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JPanel jPanel2;
//    // End of variables declaration//GEN-END:variables
//}
